// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMU2RTOfTG7z2LgOY0MkZsos2CLnbqSVA',
    appId: '1:563845824237:web:ca668bce85173e058556e4',
    messagingSenderId: '563845824237',
    projectId: 'lumos-e7a1a',
    authDomain: 'lumos-e7a1a.firebaseapp.com',
    storageBucket: 'lumos-e7a1a.firebasestorage.app',
    measurementId: 'G-XYQ4HXMM3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBltACZqPo1t67pcnIofXATwqFu2uD62L8',
    appId: '1:563845824237:android:ee91878deb8f49608556e4',
    messagingSenderId: '563845824237',
    projectId: 'lumos-e7a1a',
    storageBucket: 'lumos-e7a1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA67RrmClda3n2nS7EDxTHA4UXfd1qvbHs',
    appId: '1:563845824237:ios:fc63d972ac5ce5028556e4',
    messagingSenderId: '563845824237',
    projectId: 'lumos-e7a1a',
    storageBucket: 'lumos-e7a1a.firebasestorage.app',
    iosBundleId: 'com.example.lumos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA67RrmClda3n2nS7EDxTHA4UXfd1qvbHs',
    appId: '1:563845824237:ios:fc63d972ac5ce5028556e4',
    messagingSenderId: '563845824237',
    projectId: 'lumos-e7a1a',
    storageBucket: 'lumos-e7a1a.firebasestorage.app',
    iosBundleId: 'com.example.lumos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMU2RTOfTG7z2LgOY0MkZsos2CLnbqSVA',
    appId: '1:563845824237:web:3d1cfde88fcb8c148556e4',
    messagingSenderId: '563845824237',
    projectId: 'lumos-e7a1a',
    authDomain: 'lumos-e7a1a.firebaseapp.com',
    storageBucket: 'lumos-e7a1a.firebasestorage.app',
    measurementId: 'G-2SCNDBXM7R',
  );
}
